sudo: false

language: node_js

node_js:
    - "node"
    - "10.13.0"

branches:
    only:
        - master
        - dev

before_script:
    - make setup_cover

script:
    - yarn lint && yarn test

after_script:
    - make send_cover

notifications:
    email: false
